# Generated by Django 2.1.7 on 2019-03-21 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.IntegerField(null=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StoryMainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('synopsis', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='chapterpage',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.StoryMainPage'),
        ),
    ]
