# Generated by Django 2.1.7 on 2019-03-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190321_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterpage',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.StoryMainPage'),
        ),
    ]
