# Generated by Django 2.1.7 on 2019-03-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190321_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterpage',
            name='story',
        ),
    ]
