# Generated by Django 2.1.7 on 2019-03-21 19:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('index', '0005_auto_20190321_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryMainPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='chapterpage',
            options={'verbose_name': 'chapterpage'},
        ),
        migrations.AlterModelOptions(
            name='storyindexpage',
            options={'verbose_name': 'indexpage'},
        ),
        migrations.AlterModelOptions(
            name='storymainpage',
            options={'verbose_name': 'storypage'},
        ),
        migrations.AlterField(
            model_name='storymainpage',
            name='synopsis',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='storymainpagegalleryimage',
            name='story',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='index.StoryMainPage'),
        ),
        migrations.AddField(
            model_name='chapterpagegalleryimage',
            name='story',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='index.ChapterPage'),
        ),
    ]
