# Generated by Django 2.1.7 on 2019-03-21 19:48

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190321_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterpagegalleryimage',
            name='story',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_images', to='index.ChapterPage'),
        ),
        migrations.AlterField(
            model_name='storymainpagegalleryimage',
            name='story',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_images', to='index.StoryMainPage'),
        ),
    ]
