# Generated by Django 2.1.7 on 2019-03-22 18:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('index', '0012_auto_20190322_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='StoryCategory',
            new_name='ContentCategory',
        ),
        migrations.AlterField(
            model_name='blogarticlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='index.ArticleTags', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='articletags',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='index.BlogArticlePage'),
        ),
        migrations.AddField(
            model_name='articletags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_articletags_items', to='taggit.Tag'),
        ),
    ]
