# Generated by Django 2.1.7 on 2019-04-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('index', '0013_auto_20190322_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='chapterpage',
            options={'verbose_name': 'Chapter Page'},
        ),
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'verbose_name': 'Story Category'},
        ),
        migrations.AlterModelOptions(
            name='storyindexpage',
            options={'verbose_name': 'Story Index Page'},
        ),
        migrations.AlterModelOptions(
            name='storymainpage',
            options={'verbose_name': 'Story Main Page'},
        ),
    ]
