# Generated by Django 2.1.7 on 2019-04-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20190402_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'verbose_name': 'Content Category'},
        ),
    ]
