# Generated by Django 2.1.7 on 2019-04-02 20:21

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20190402_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoryindexpage',
            name='one_line',
            field=models.CharField(default='', max_length=100),
        ),
    ]
