# Generated by Django 2.1.7 on 2019-04-02 20:27

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20190402_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryindexpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='categoryindexpage',
            name='one_line',
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='one_line',
            field=models.CharField(default='', max_length=100),
        ),
    ]
